### PR TITLE
Fixed bug in the order of the parameters

### PR DESCRIPTION
**Pull request by pcolladosoto**
This PR hopefully fixes issue #21.

### CODE REVIEW

**Comment by pcolladosoto** [comment]
Note the tests are failing because the arguments passed in `test_eol.py` used the old order (i.e. the language is the second argument). In order for everything to be pretty we could either change the tests or alter the order of both calls in `tidyup.py`. I altered `fix_steps()`'s prototype as I prefer having the language as the last argument but it's just a matter of style.

I didn't want to change tests that weren't mine... What do you think @wheleph? Should we change the parameter order on your tests or just change the call to fix_step()?

Sorry for all the hassle...

**Comment by wheleph** [comment]
Great find!

I personally prefer having `lang` as a second argument because it's a kind of "input" argument just like `src`. `dst` is on the other hand is "output" argument. I put "input" and "output" in quotes because from the language perspective both of them are input arguments.

The issue was also spotted and fixed by @robertjank in https://github.com/wheleph/nttt/pull/20/files

Please don't hesitate to change any code (including tests). That's why we have the review step in our process. Non-shared code ownership is harmful for everyone: https://www.freecodecamp.org/news/why-code-ownership-sucks-and-you-should-never-work-somewhere-that-practices-it-b8fc1c694074/

**Comment by pcolladosoto** [comment]
Thanks for the comment! I took a look at the article you linked and it proved to be very interesting :smile_cat:! I also get your choice in the order of the parameters... My general approach is to have the "main" "input" and "output" parameters first and any "auxiliary" parameters after that, but I see your preference is less error prone than mine.

Anyway, as @robertjank has already fixed it (as it was taken care of in an "unrelated" PR I didn't think that would be the case) I'll close this PR. Knowing @robertjank followed your schema all the tests are passing so I believe that to be better. I'll also reassign issue #21 to him.

Thanks again for the input!

**Comment by robertjank** [comment]
Nice read, @wheleph! See also https://blog.codinghorror.com/the-ten-commandments-of-egoless-programming/

**Pull request closed without merging**
